// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	ENVIRONMENT: "production" | "development";
	RATE_LIMITER: DurableObjectNamespace<import("./src/index").RateLimiter>;
	R2: R2Bucket;
	DB: D1Database;
}
